module.exports = {
  header_sample: [
    {
      name: 'None',
      require: false,
      content: false,
      defValue: '',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: '№',
      require: true,
      content: 'number',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
    },
    {
      name: 'Ник',
      require: true,
      content: 'string',
      defValue: 'Anonimous',
      depForSetDefault: true,
      calculate: false,
    },
    {
      name: 'Марка',
      require: false,
      content: 'string',
      defValue: '',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'Название вещи',
      require: false,
      content: 'string',
      defValue: '',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'Ссылка',
      require: false,
      content: 'string',
      defValue: '',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'Цвет',
      require: false,
      content: 'string',
      defValue: '',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'Размер',
      require: false,
      content: 'string',
      defValue: '',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'Цена',
      require: true,
      content: 'number',
      defValue: '0',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'Количество',
      require: true,
      content: 'number',
      defValue: '1',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'Вес',
      require: false,
      content: 'number',
      defValue: '',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'Категория цен',
      require: true,
      content: 'number',
      defValue: '1',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'Примечание',
      require: false,
      content: 'string',
      defValue: '',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'Итого',
      require: true,
      content: 'number',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
    },
    {
      name: 'Доставка',
      require: false,
      content: 'number',
      defValue: '',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'К оплате',
      require: true,
      content: 'number',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
    },
  ],
  header_sample_tableWithPay: [
    {
      name: '№',
      require: true,
      content: 'number',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
    },
    {
      name: 'Ник',
      require: true,
      content: 'string',
      defValue: 'Anonimous',
      depForSetDefault: true,
      calculate: false,
    },
    {
      name: 'Сумма платежа',
      require: true,
      content: 'number',
      defValue: '0',
      depForSetDefault: true,
      calculate: false,
    },
    {
      name: 'Дата учета',
      require: true,
      content: 'date',
      defValue: '',
      depForSetDefault: false,
      calculate: false,
    },
    {
      name: 'Примечание',
      require: false,
      content: 'string',
      defValue: '',
      depForSetDefault: false,
      calculate: false,
    },
  ],
  orders: [],
  purchases: [],
  users: [],
  incomingPayments: [],
  outgoingPayments: [],
  headersGoogleSheetsWithRepliesAboutPayments: [
    {
      name: '№',
      require: true,
      content: 'number',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
      index: 0,
      display: true,
    },
    {
      name: 'Отметка времени',
      require: true,
      content: 'date',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
      index: 1,
      display: true,
    },
    {
      name: 'Ник',
      require: true,
      content: 'string',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
      index: 2,
      display: true,
    },
    {
      name: 'Сумма',
      require: true,
      content: 'number',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
      index: 3,
      display: true,
    },
    {
      name: 'Дата',
      require: true,
      content: 'date',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
      index: 4,
      display: true,
    },
    {
      name: 'Способ оплаты',
      require: true,
      content: 'string',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
      index: 5,
      display: true,
    },
    {
      name: 'Название закупки',
      require: true,
      content: 'string',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
      index: 6,
      display: true,
    },
    {
      name: 'Примечание',
      require: true,
      content: 'string',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
      index: 7,
      display: true,
    },
    {
      name: 'Данные владельца карты',
      require: true,
      content: 'string',
      defValue: '',
      depForSetDefault: true,
      calculate: false,
      index: 8,
      display: true,
    },

  ],
};
